### ISSUE TITLE
Example of how to migrate to safe

### ISSUE THREAD

**Issue by stevenspiel** [MixinNetwork/mixin_bot_sdk_dart#122]
I was hoping you could provide an example of how to successfully migrate a user.

Here is a step in the right direction, I hope, but I'm surely doing a few things incorrectly.

```dart
import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:convert/convert.dart';
import 'package:edwards25519/edwards25519.dart';
import 'package:mixin_bot_sdk_dart/mixin_bot_sdk_dart.dart';

void main() async {
  const pin = '000000';
  final client = Client(
    userId: '24ff159b-151f-3e1a-9e6a-eca8501c3f27',
    sessionId: 'c1120a82-808d-4794-9880-deae71820cfe',
    privateKey:
        'H20K7V+D0ouD4/gkqECRR/zw4rIBnIJTTYyWCwVvVEM3biu4y2iuLgipsdJV76n1mz/uxoYsqOXABo9t72Zhug==',
    httpLogLevel: null,
  );

  final me = await client.dio.get('/safe/me');
  final hasSafe = me.data['data']['has_safe'] as bool;

  if (hasSafe) {
    print('User has been migrated');
  } else {
    print('User has not been migrated');

    // Generate a new key pair

    final ed25519 = Ed25519();
    final seed =
        '73a58e0f5f7e2b7143c8664c917f0de86dddb5c683e9d8762a7c1c0c30cc0333';
    final key = await ed25519.newKeyPairFromSeed(hex.decode(seed));
    final ed25519Key =
        '$seed${hex.encode((await key.extractPublicKey()).bytes)}';
    final keyFromSeed = Scalar()..setUniformBytes(hex.decode(ed25519Key));

    print(
        'ed25519_key: $seed${hex.encode((await key.extractPublicKey()).bytes)}');
    print('seed: $seed');
    print('key: ${hex.encode(keyFromSeed.Bytes())}'); // <- I'm not confident this is correct

    // Sign PIN

    final privateKey = PrivateKey(Uint8List.fromList(hex.decode(seed)));
    final timestamp = DateTime.now().millisecondsSinceEpoch * 1000000;
    final tipBody = 'TIP:VERIFY:${timestamp.toString().padLeft(32, '0')}';
    final signature = privateKey.sign(Uint8List.fromList(hex.decode(tipBody)));
    final encryptedPin = encryptPin(
      pin,
      base64Encode(signature),
      hex.encode(privateKey.bytes),
      0,
    ); // <- I'm not confident this is correct

    // Verify pin

    final verificationResponse = await client.dio.post('/pin/verify', data: {
      'timestamp': timestamp,
      'pin_base64': encryptedPin,
    });
    print(verificationResponse.data);

    // Update pin

    final updateResponse = await client.dio.post('/pin/update', data: {
      'pin': encryptedPin,
    });
    print(updateResponse.data);

    // Migrate user

    final migrateResponse = await client.utxoApi.registerPublicKey(
      publicKey: ed25519Key,
      signature: hex.encode(signature),
      pin: encryptedPin,
      salt: '',
    );
    print(migrateResponse.data);
  }
}
```

When running the above code, the output is this:

```bash
User has not been migrated
ed25519_key: 73a58e0f5f7e2b7143c8664c917f0de86dddb5c683e9d8762a7c1c0c30cc03338be06d3938fc1065d631469f3e46b5e442a56f4c8d3678d02cf9838d10659040
seed: 73a58e0f5f7e2b7143c8664c917f0de86dddb5c683e9d8762a7c1c0c30cc0333
key: 698980d9a38c6b3b219c2028032843ae09459e22b50958cf6b8d6e944929e50e
Unhandled exception:
FormatException: Invalid input length, must be even. (at character 44)
TIP:VERIFY:00000000000001704829918463000000
                                           ^

#0      HexDecoder.convert (package:convert/src/hex/decoder.dart:26:7)
#1      Codec.decode (dart:convert/codec.dart:30:34)
#2      main (package:mixinmigrate/main.dart:47:62)
<asynchronous suspension>
```

**Comment by boyan01** [comment]
@stevenspiel  you can follow the `example/safe_upgrade.dart` in #123

**Comment by stevenspiel** [comment]
Ahhh amazing!! Thank you so much!
